### ISSUE TITLE
supxlabel etc

### ISSUE THREAD

**Issue by mhardcastle** [tikk3r/lofar-h5plot#25]
A very minor thing but supxlabel, supylabel are only supported in recent versions of matplotlib. For those of us stuck running native Python 3.6 it would be nice if the code gracefully failed to plot the labels on waterfall plots (it's perfectly clear what the axes are) by catching AttributeError.

**Comment by tikk3r** [comment]
Thanks for reporting this. I have pushed an attempted fix to master.
