### ISSUE TITLE
Weight plotting bug

### ISSUE THREAD

**Issue by jurjen93** [tikk3r/lofar-h5plot#28]
Displaying the weights resets the weights to 1 in the plot after moving through the antenna plots. Also going back and forth gives me first weights 0 (which is correct) and then weights 1 (which is incorrect) for the same antenna:
![image](https://github.com/tikk3r/lofar-h5plot/assets/18346230/bccb6f95-1fd5-4862-92f7-d829e9d68004)
![image](https://github.com/tikk3r/lofar-h5plot/assets/18346230/3dc92d22-ac1e-4ba6-aeed-57848c1cf45c)

**Comment by tikk3r** [comment]
Thanks. I've pushed an attempted fix to https://github.com/tikk3r/lofar-h5plot/pull/29 if you want to try.
