### ISSUE TITLE
Plot weights with all stations seems to swap freq and time axis

### ISSUE THREAD

**Issue by rvweeren** [tikk3r/lofar-h5plot#30]
Plot weights with all stations seems to swap freq and time axis?

I see strange inconsistencies when plotting the weights. For example, if I plot a single station I see this:
<img width="412" alt="image" src="https://github.com/tikk3r/lofar-h5plot/assets/3879473/f00c2ca8-f1af-4a55-a772-0339b338865c">

But then if I plot all stations  I see this and the weights look rotated:
<img width="770" alt="image" src="https://github.com/tikk3r/lofar-h5plot/assets/3879473/c4b95154-2bdc-4952-be1f-7f93f199a2cd">

I'm not fully sure, but I think the "all station" plot is wrong and the "single station" plot is correct.

**Comment by tikk3r** [comment]
I think the single station plot is correct indeed. All stations seems to (not) tranpose the data.

**Comment by tikk3r** [comment]
I think it was a simple fix, implemented in #31. You should be able to simply download the `h5plot` file from that branch to test.

**Comment by tikk3r** [comment]
Fixed with #31.
