### ISSUE TITLE
Inverted plots, when plotting all stations

### ISSUE THREAD

**Issue by jurjen93** [tikk3r/lofar-h5plot#33]
When, I plot all station weights, the frequency and time axes are swapped.
Also, the colorbar is a bit strange (going from -0.1 to 0.1)
![image](https://github.com/tikk3r/lofar-h5plot/assets/18346230/38c2dc0d-2f0b-4e1f-83df-ef24840e61fa)
It is correct for individual station plots:
![image](https://github.com/tikk3r/lofar-h5plot/assets/18346230/623ba1b2-fec8-450a-b554-b12fec97e9c6)

**Comment by tikk3r** [comment]
It sounds familiar to #30. Is it by any chance fixed for you on master?

**Comment by jurjen93** [comment]
Oh, oops! My bad, I didnt use the latest master :)
